project:
  type: website
  output-dir: docs

website:
  title: "malariaverse"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: More information
      - resources.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

