project:
  type: website
  output-dir: docs

website:
  title: "malariaverse"
  navbar:
    logo: "images/malariaverse_white.png"
    left:
      - href: index.qmd
        text: Home
      - href: tutorial.qmd
        text: Tutorial
      - href: advanced_tutorial.qmd
        text: Advanced tutorial
      - href: about.qmd
        text: More information
      - resources.qmd
  page-footer:
    left: "This website was created with ❤️ and [Quarto](https://quarto.org/) by [Pete Winskill](mailto:p.winskill@imperial.ac.uk). Some [image credits](https://rawpixel.com)"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual
