project:
  type: website
  output-dir: docs

website:
  title: "malariaverse"
  navbar:
    logo: "images/malariaverse_white.png"
    left:
      - href: index.qmd
        text: Home
      - href: onboard.qmd
        text: New starters!
      - href: tutorial1.qmd
        text: Tutorial - part 1
      - href: tutorial2.qmd
        text: Tutorial - part 2
      - href: tutorial3.qmd
        text: Tutorial - part 3
      - href: about.qmd
        text: More information
  page-footer:
    left: "This website was created with ❤️ and [Quarto](https://quarto.org/) by [Pete Winskill](mailto:p.winskill@imperial.ac.uk)."

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual
